allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  prisma: true

enablePrePostScripts: true
strictPeerDependencies: false

packages:
  - packages/*
  - packages/foundation/tools/*

minimumReleaseAgeExclude:
  - '@commitlint/cli@21.0.2'
  - '@commitlint/config-conventional@21.0.2'
  - '@commitlint/is-ignored@21.0.2'
  - '@commitlint/lint@21.0.2'
  - '@commitlint/load@21.0.2'
  - '@commitlint/message@21.0.2'
  - '@commitlint/parse@21.0.2'
  - '@commitlint/prompt-cli@21.0.2'
  - '@commitlint/prompt@21.0.2'
  - '@commitlint/read@21.0.2'
  - '@commitlint/rules@21.0.2'
  - '@commitlint/top-level@21.0.2'
  - '@inversifyjs/foundation-eslint-config@0.3.0'
